Repository Kristiannmiller/hang-in-there-boilerplate, pull requests merged in 2020-07, with the labels that each got.

#3 Feature/switching views
  src/main.js
Labels: enhancement

#4 Add updated readme
  README.md
Labels: documentation, enhancement

#5 Add project progression notes to readme file
  README.md
Labels: documentation

#7 Feature/create new poster from form
  src/main.js
Labels: documentation, enhancement

#8 Feature/saving and viewing posters
  src/main.js
Labels: enhancement

#9 Create addSavedPosterToGrid function
  src/main.js
Labels: enhancement

#10 Feature/dry functional code
  src/main.js
Labels: enhancement

#11 Feature/push to array ternaries
  README.md
  src/main.js
Labels: documentation, enhancement

#12 Complete README by adding images and videos of site functionality.
  README.md
  readme-imgs/Form-View-HIT.png
  readme-imgs/Main-Poster-Page-HIT.png
  readme-imgs/Poster-From-Form-HIT.png
  readme-imgs/Saved-Poster-HIT.png
Labels: documentation, enhancement
